### ISSUE TITLE
Restrict $BOOTSTRAP_VERBOSITY

### ISSUE THREAD

**Issue by zupo** [niteoweb/heroku-buildpack-buildout#12]
Currently, one can put *anything* into the $BOOTSTRAP_VERBOSITY env and it will get run inline. 

It's better if we restrict it to only -v, -vv, -vvv, etc.

**Comment by vietdt** [comment]
Should we implement the same for $BUILDOUT_VERBOSITY?

One note, current bootstrap.py is using "-v" for setting zc.buildout version. So it will fail if we run test with $BOOTSTRAP_VERBOSITY env set to "-v". I think we should update it to use "-v" for verbosity and only "--version" to set zc.buildout version.

**Comment by zupo** [comment]
Yes and yes.
