### ISSUE TITLE
Push Rejected, failed to compile Multipack app.

### ISSUE THREAD

**Issue by rvanlaar** [niteoweb/heroku-buildpack-buildout#4]
I'm running into a problem creating of having a buildout/django heroku app.
How can I fix this?

The example app which generates this problem: https://github.com/rvanlaar/heroku-buildout.git
$ cd heroku-buildout
$ heroku create
$ heroku config:set BUILDPACK_URL=https://github.com/ddollar/heroku-buildpack-multi.git
$ git push heroku master

....
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching custom git buildpack... done
remote: -----> Multipack app detected
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-python.git
remote: 
remote:  !     Push rejected, failed to compile Multipack app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to

**Comment by zupo** [comment]
Heroku now official supports multiple buildpacks: https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app
